<?php

namespace AppBundle\Tests\Controller;
use Tests\AppBundle\Controller\BaseControllerTest;

class UserControllerTest extends BaseControllerTest
{
    public function testLoginShowUser()
    {
        $this->testLogin('abc4'); // TODO: Change the autogenerated stub

        $this->client->request('GET', 'http://localhost/profile/abc4');

        $this->assertContains('Details', $this->client->getResponse()->getContent());
        //'Details' is found means the user 'abc4' details page shows up

    }

}
